name: Build GHCR images

on:
  workflow_call:
  pull_request_target:
    branches: ["master"]
    paths:
      - "**/*"
      - "!.github/**" # Important: Exclude PRs related to .github from auto-run
      - "!.github/workflows/**" # Important: Exclude PRs related to .github/workflows from auto-run
      - "!.github/actions/**" # Important: Exclude PRs related to .github/actions from auto-run

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  check_paths:
    if: ${{ github.event_name != 'workflow_call' }}
    uses: ./.github/workflows/check_paths.yml

  teslamate_build:
    name: Build images
    needs: check_paths
    # Only run if there are no changes to the github folder and on workflow call, or PRs from forks (to avoid duplicate runs for PRs from non-forks, and to avoid invalid reference format for cache name in PRs from our repo)
    if: needs.check_paths.outputs.githubfolder != 'true' && (${{ github.event_name  == 'workflow_call' }} || ${{ github.event.pull_request.head.repo.full_name }} != ${{ github.repository }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "linux/amd64"
            runs_on: "ubuntu-24.04"
            cache_id: amd64

    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        if: ${{ github.event_name != 'pull_request_target' }}
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Buildx
        uses: ./.github/actions/build
        with:
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.head_ref || github.ref_name }}
          labels: |
            org.opencontainers.image.version=${{ github.ref || github.ref_name }}

  teslamate_merge:
    name: Merge GHCR images
    needs:
      - check_paths
      - teslamate_build
    if: needs.check_paths.outputs.githubfolder != 'true'
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge
        id: merge
        uses: ./.github/actions/merge
        with:
          image: ${{ env.REGISTRY_IMAGE }}

  grafana:
    needs: check_paths
    # Only run if there are no changes to the github folder and on workflow call, or PRs from forks (to avoid duplicate runs for PRs from non-forks, and to avoid invalid reference format for cache name in PRs from our repo)
    if: needs.check_paths.outputs.githubfolder != 'true' && (${{ github.event_name  == 'workflow_call' }} || ${{ github.event.pull_request.head.repo.full_name }} != ${{ github.repository }})
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        if: ${{ github.event_name != 'pull_request_target' }}
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/grafana
        with:
          image: ${{ env.REGISTRY_IMAGE }}/grafana
          labels: |
            org.opencontainers.image.version=${{ github.ref || github.ref_name }}
